"""create messages

Revision ID: a4326b105527
Revises: 397c6808b350
Create Date: 2025-09-15 14:39:36.086384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4326b105527'
down_revision = '397c6808b350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', sa.DATETIME(), nullable=False))
    op.alter_column('messages', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
